### ISSUE TITLE
很好用, 谢谢黄哥

### ISSUE THREAD

**Issue by snaillovesmile** [huangchangweng/HLCryptor#1]

**Comment by SnailLoveSmile** [comment]
或者我把 这个加密错的文本 信息写在这 发面 测试: 
加密文本: 712a2d0391d56a5e0f2da218d1c1e035
加密方式: DES
偏移量: 00000000
加密key: INCH@20221705893193646
我们的加密结果: hUZoh23sl99FDCncRQmInk3djxZh13ggQG8cHH3u4T3qWPt9n7fNpA==
对的应该是:
